services:
  litchi:
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - tcl_user
        - tcl_pass
    ports:
      - 8000:8000
    env_file: ".env"

secrets:
  tcl_pass:
    environment: TCL_PASS
  tcl_user:
    environment: TCL_USER